---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/apukap/Juggled # default
          #username: apukap
          #password: apukap
          search-paths:
            - 'centralFilling'
